name: dart_ffi_template
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  ffi: ^2.1.0
  ffigen: ^19.0.0

  flutter:
    sdk: flutter

dev_dependencies:

################################ flutter #######################################
flutter:

  plugin:
    platforms:
      windows:
        ffiPlugin: true

################################ ffigen ########################################
# Run with `dart run ffigen`
ffigen:
  name: "dart_ffi_template"
  description: "bindings"
  output: "lib/bindings.dart"
  preamble: |
    // ignore_for_file: type=lint, unused_element, unused_field

  llvm-path:
    - C:\ProgramFiles\Library\clangllvm

  headers:
    entry-points:
      - "src/export.h"
    # include-directives:
    #   - "src/**"
